name: ashes_cricket
description: Cricket A7 Live Score App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_database: ^10.3.7
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
