name: Build Flutter APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Flutter Doctor
        run: flutter doctor

      - name: Recreate Flutter Project Cleanly
        run: |
          rm -rf temp_app
          flutter create temp_app
          cp -r lib temp_app/
          cp pubspec.yaml temp_app/
          cd temp_app

      - name: Install dependencies
        run: |
          cd temp_app
          flutter pub get

      - name: Build APK
        run: |
          cd temp_app
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: temp_app/build/app/outputs/flutter-apk/app-release.apk
